apiVersion: v1
kind: Service
metadata:
  name: excuseme-loadbalancer
spec:
  selector:
    app: excuseme-wa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer